// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325160206_AddDaXoaToDanhMuc")]
    partial class AddDaXoaToDanhMuc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BaiGiang", b =>
                {
                    b.Property<int>("MaBaiGiang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiGiang"));

                    b.Property<bool>("DangKhoa")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiBaiGiang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaChuong")
                        .HasColumnType("int");

                    b.Property<Guid?>("MaTaiNguyen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TyLeXemToiThieu")
                        .HasColumnType("int");

                    b.Property<bool>("XemMienPhi")
                        .HasColumnType("bit");

                    b.HasKey("MaBaiGiang");

                    b.HasIndex("MaChuong");

                    b.HasIndex("MaTaiNguyen");

                    b.ToTable("BaiGiangs");
                });

            modelBuilder.Entity("backend.Models.BaiKiemTra", b =>
                {
                    b.Property<int>("MaBaiKiemTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiKiemTra"));

                    b.Property<decimal>("DiemDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GioiHanThoiGianPhut")
                        .HasColumnType("int");

                    b.Property<int>("MaBaiGiang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLanToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("XaoTronNgauNhien")
                        .HasColumnType("bit");

                    b.HasKey("MaBaiKiemTra");

                    b.HasIndex("MaBaiGiang");

                    b.ToTable("BaiKiemTras");
                });

            modelBuilder.Entity("backend.Models.CauHinhHeThong", b =>
                {
                    b.Property<string>("KhoaCauHinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CapNhatBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GiaTriCauHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KieuDuLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("KhoaCauHinh");

                    b.ToTable("CauHinhHeThongs");

                    b.HasData(
                        new
                        {
                            KhoaCauHinh = "PhiNenTang",
                            GiaTriCauHinh = "30",
                            KieuDuLieu = "Decimal",
                            MoTa = "Tỷ lệ % phí nền tảng giữ lại từ mỗi đơn hàng"
                        },
                        new
                        {
                            KhoaCauHinh = "MaxUploadSizeMB",
                            GiaTriCauHinh = "2048",
                            KieuDuLieu = "Int",
                            MoTa = "Giới hạn dung lượng tệp tải lên (MB)"
                        },
                        new
                        {
                            KhoaCauHinh = "ThoiGianGiuTienNgay",
                            GiaTriCauHinh = "30",
                            KieuDuLieu = "Int",
                            MoTa = "Số ngày giữ tiền trước khi giải phóng cho giảng viên"
                        },
                        new
                        {
                            KhoaCauHinh = "DiemToiThieuRutTien",
                            GiaTriCauHinh = "100000",
                            KieuDuLieu = "Decimal",
                            MoTa = "Số dư tối thiểu (VNĐ) để giảng viên có thể rút"
                        });
                });

            modelBuilder.Entity("backend.Models.CauHoi", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHoi"));

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiCauHoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaBaiKiemTra")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCauHoi");

                    b.HasIndex("MaBaiKiemTra");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("backend.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDonHang"));

                    b.Property<decimal>("GiaTaiThoiDiemMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiamGiaApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaChiTietDonHang");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("backend.Models.ChienDich", b =>
                {
                    b.Property<int>("MaChienDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChienDich"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanBanner")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaoBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChienDich")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MaChienDich");

                    b.HasIndex("TaoBoi");

                    b.ToTable("ChienDichs");
                });

            modelBuilder.Entity("backend.Models.ChuDeHoiDap", b =>
                {
                    b.Property<int>("MaChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuDe"));

                    b.Property<bool>("DaGiaiDap")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("MaBaiGiang")
                        .HasColumnType("int");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuotUpvote")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaChuDe");

                    b.HasIndex("MaBaiGiang");

                    b.HasIndex("MaHocVien");

                    b.ToTable("ChuDeHoiDaps");
                });

            modelBuilder.Entity("backend.Models.ChungChi", b =>
                {
                    b.Property<Guid>("MaChungChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanPDFChungChi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaXacThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayCapPhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChungChi");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("ChungChis");
                });

            modelBuilder.Entity("backend.Models.ChuoiHocLienTiep", b =>
                {
                    b.Property<int>("MaChuoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuoi"));

                    b.Property<int>("ChuoiDaiNhat")
                        .HasColumnType("int");

                    b.Property<int>("ChuoiHienTai")
                        .HasColumnType("int");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoatDongCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TheDoangBang")
                        .HasColumnType("int");

                    b.HasKey("MaChuoi");

                    b.HasIndex("MaHocVien");

                    b.ToTable("ChuoiHocLienTieps");
                });

            modelBuilder.Entity("backend.Models.Chuong", b =>
                {
                    b.Property<int>("MaChuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuong"));

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaChuong");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("Chuongs");
                });

            modelBuilder.Entity("backend.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<bool>("BiBaoCao")
                        .HasColumnType("bit");

                    b.Property<bool>("DaMuaKhoaHoc")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("DiemSao")
                        .HasColumnType("int");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("backend.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<bool>("DangHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanIcon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DuongDanURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("MaDanhMucCha");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("backend.Models.DapAnHocVien", b =>
                {
                    b.Property<int>("MaDapAnChon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDapAnChon"));

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<int>("MaLanLam")
                        .HasColumnType("int");

                    b.Property<int?>("MaLuaChonDaChon")
                        .HasColumnType("int");

                    b.HasKey("MaDapAnChon");

                    b.HasIndex("MaCauHoi");

                    b.HasIndex("MaLanLam");

                    b.HasIndex("MaLuaChonDaChon");

                    b.ToTable("DapAnHocViens");
                });

            modelBuilder.Entity("backend.Models.DiemDanh", b =>
                {
                    b.Property<long>("MaDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaDiemDanh"));

                    b.Property<DateTime?>("DiemDanhLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HopLe")
                        .HasColumnType("bit");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaLichHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLichHoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianXemThucTeGiay")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDiemDanh");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("MaLichHoc");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("backend.Models.DonHang", b =>
                {
                    b.Property<string>("MaDonHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CongThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DonViTienTe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaGiaoDichCong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThanhToanLuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaHocVien");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("backend.Models.GhiChu", b =>
                {
                    b.Property<int>("MaGhiChu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhiChu"));

                    b.Property<int>("MaBaiGiang")
                        .HasColumnType("int");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiDiem")
                        .HasColumnType("int");

                    b.HasKey("MaGhiChu");

                    b.HasIndex("MaBaiGiang");

                    b.HasIndex("MaHocVien");

                    b.ToTable("GhiChus");
                });

            modelBuilder.Entity("backend.Models.GhiDanh", b =>
                {
                    b.Property<int>("MaGhiDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhiDanh"));

                    b.Property<DateTime>("GhiDanhLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDonHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThuHoiLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiTruyCap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGhiDanh");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("GhiDanhs");
                });

            modelBuilder.Entity("backend.Models.GiamGia", b =>
                {
                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaGiamGia");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<decimal>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GioiHanLuotDung")
                        .HasColumnType("int");

                    b.Property<int>("LoaiGiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaChienDich")
                        .HasColumnType("int");

                    b.Property<Guid?>("MaGiangVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuotDaDung")
                        .HasColumnType("int");

                    b.HasKey("MaGiamGia");

                    b.HasIndex("MaChienDich");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("MaGiamGia");
                });

            modelBuilder.Entity("backend.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaHocVien");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("backend.Models.HoSoGiangVien", b =>
                {
                    b.Property<Guid>("MaGiangVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DanhHieu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DuongDanLinkedIn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DuongDanWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("KyKetDieuKhoanLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSoThueMaHoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinNganHangMaHoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuSuChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiKYC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TyLeDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaGiangVien");

                    b.ToTable("HoSoGiangViens");
                });

            modelBuilder.Entity("backend.Models.HoSoNhanVien", b =>
                {
                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MaNhanVienNoiBo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongBan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuyenBoSung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNoiBo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("HoSoNhanViens");
                });

            modelBuilder.Entity("backend.Models.HoanTien", b =>
                {
                    b.Property<int>("MaHoanTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoanTien"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienHoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("XuLyBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("XuLyLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHoanTien");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("XuLyBoi");

                    b.ToTable("HoanTiens");
                });

            modelBuilder.Entity("backend.Models.KhoaHoc", b =>
                {
                    b.Property<Guid>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiemDanhGiaTrungBinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DuongDanAnhDaiDien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DuongDanURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChuTuChoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LuuTruLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<Guid>("MaGiangVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaVideoGioiThieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucTieuDauRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDeNho")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TongBaiGiang")
                        .HasColumnType("int");

                    b.Property<int>("TongDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("TongGhiDanh")
                        .HasColumnType("int");

                    b.Property<int>("TongThoiLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("XuatBanLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("YeuCauDieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoaHoc");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaVideoGioiThieu");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("backend.Models.LanDangNhap", b =>
                {
                    b.Property<long>("MaLanLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLanLam"));

                    b.Property<DateTime>("BatDauLamLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangNhapThanhCong")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDoThatBai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrinhDuyet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaLanLam");

                    b.ToTable("LanDangNhaps");
                });

            modelBuilder.Entity("backend.Models.LanLamBai", b =>
                {
                    b.Property<int>("MaLanLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLanLam"));

                    b.Property<DateTime>("BatDauLamLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaDat")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaBaiKiemTra")
                        .HasColumnType("int");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NopBaiLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoCauDung")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiGianLamGiay")
                        .HasColumnType("int");

                    b.Property<int>("TongCauHoi")
                        .HasColumnType("int");

                    b.HasKey("MaLanLam");

                    b.HasIndex("MaBaiKiemTra");

                    b.HasIndex("MaHocVien");

                    b.ToTable("LanLamBais");
                });

            modelBuilder.Entity("backend.Models.LichHoc", b =>
                {
                    b.Property<int>("MaLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHoc"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<Guid>("MaHocVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgayTrongTuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThoiLuongToiThieuPhut")
                        .HasColumnType("int");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LichHocs");
                });

            modelBuilder.Entity("backend.Models.LuaChonDapAn", b =>
                {
                    b.Property<int>("MaLuaChon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuaChon"));

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungLuaChon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaLuaChon");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("LuaChonDapAns");
                });

            modelBuilder.Entity("backend.Models.MaHoaVideo", b =>
                {
                    b.Property<int>("MaMaHoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMaHoa"));

                    b.Property<string>("DoPhanGiai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DuongDanHLS")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("MaHoaLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaTaiNguyen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TocDoBitKbps")
                        .HasColumnType("int");

                    b.HasKey("MaMaHoa");

                    b.HasIndex("MaTaiNguyen");

                    b.ToTable("MaHoaVideos");
                });

            modelBuilder.Entity("backend.Models.MaOtp", b =>
                {
                    b.Property<int>("MaToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaToken"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("GiaTriToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("HetHanLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaToken");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("MaOtps");
                });

            modelBuilder.Entity("backend.Models.MatHangGioHang", b =>
                {
                    b.Property<int>("MaMatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMatHang"));

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThemVaoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaMatHang");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("MatHangGioHangs");
                });

            modelBuilder.Entity("backend.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailDaXacThuc")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LaNhanVien")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhauBam")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MuoiMatKhau")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("backend.Models.NhanKhoaHoc", b =>
                {
                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhoaHoc", "MaNhan");

                    b.HasIndex("MaNhan");

                    b.ToTable("NhanKhoaHocs");
                });

            modelBuilder.Entity("backend.Models.NhanTuKhoa", b =>
                {
                    b.Property<int>("MaNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhan"));

                    b.Property<string>("DuongDanURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuotDung")
                        .HasColumnType("int");

                    b.Property<string>("TenNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhan");

                    b.ToTable("NhanTuKhoas");
                });

            modelBuilder.Entity("backend.Models.NhatKyKiemToan", b =>
                {
                    b.Property<long>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLog"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTriMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LoaiDoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrinhDuyet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaLog");

                    b.ToTable("NhatKyKiemToans");
                });

            modelBuilder.Entity("backend.Models.PhanHoiPhieu", b =>
                {
                    b.Property<int>("MaTraLoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTraLoi"));

                    b.Property<bool>("GhiChuNoiBo")
                        .HasColumnType("bit");

                    b.Property<Guid>("MaNguoiGui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTinNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTraLoi");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaPhieu");

                    b.ToTable("PhanHoiPhieus");
                });

            modelBuilder.Entity("backend.Models.PhienLamViec", b =>
                {
                    b.Property<Guid>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaThuHoi")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HetHanLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinThietBi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TokenLamMoi")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaPhien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PhienLamViecs");
                });

            modelBuilder.Entity("backend.Models.PhieuHoTro", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DiemHaiLong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DongPhieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuLieuBoiCanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GiaiQuyetLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDonHangLienQuan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaNguoiGuiYeuCau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MucUuTien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PhanCongCho")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhanLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDeThongBao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaNguoiGuiYeuCau");

                    b.HasIndex("PhanCongCho");

                    b.ToTable("PhieuHoTros");
                });

            modelBuilder.Entity("backend.Models.SoCaiKeToan", b =>
                {
                    b.Property<long>("MaBuToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaBuToan"));

                    b.Property<bool>("DaGiaiPhong")
                        .HasColumnType("bit");

                    b.Property<decimal>("DoanhThuGop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GiaiPhongLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaGiangVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayGiaiPhong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiNenTang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThuNhapGiangVien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBuToan");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("SoCaiKeToans");
                });

            modelBuilder.Entity("backend.Models.TaiNguyenSo", b =>
                {
                    b.Property<Guid>("MaTaiNguyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DungLuongByte")
                        .HasColumnType("bigint");

                    b.Property<string>("DuongDanLuuTru")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KieuMIME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiTep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaiLenBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTep")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiNguyen");

                    b.HasIndex("TaiLenBoi");

                    b.ToTable("TaiNguyenSos");
                });

            modelBuilder.Entity("backend.Models.ThongBaoKhoaHoc", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<DateTime>("GuiLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaGiangVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDeThongBao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TongNguoiNhan")
                        .HasColumnType("int");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("ThongBaoKhoaHocs");
                });

            modelBuilder.Entity("backend.Models.ThongKeThoatBaiHoc", b =>
                {
                    b.Property<int>("MaBaiGiang")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapNhatLanCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuotHoanThanh")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotXem")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianXemTrungBinhGiay")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLeThoat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBaiGiang");

                    b.ToTable("ThongKeThoatBaiHocs");
                });

            modelBuilder.Entity("backend.Models.TienDoHocTap", b =>
                {
                    b.Property<long>("MaTienDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaTienDo"));

                    b.Property<DateTime?>("HoanThanhLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaBaiGiang")
                        .HasColumnType("int");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianXemGiay")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ViTriXemCuoi")
                        .HasColumnType("int");

                    b.HasKey("MaTienDo");

                    b.HasIndex("MaBaiGiang");

                    b.HasIndex("MaGhiDanh");

                    b.ToTable("TienDoHocTaps");
                });

            modelBuilder.Entity("backend.Models.TongHopDoanhThuNgay", b =>
                {
                    b.Property<DateTime>("NgayTongHop")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTienHoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongDonHang")
                        .HasColumnType("int");

                    b.Property<int>("TongHoanTien")
                        .HasColumnType("int");

                    b.HasKey("NgayTongHop", "MaKhoaHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("TongHopDoanhThuNgays");
                });

            modelBuilder.Entity("backend.Models.TraLoiHoiDap", b =>
                {
                    b.Property<int>("MaTraLoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTraLoi"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<bool>("DuocGhimBoi")
                        .HasColumnType("bit");

                    b.Property<int>("MaChuDe")
                        .HasColumnType("int");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuotUpvote")
                        .HasColumnType("int");

                    b.HasKey("MaTraLoi");

                    b.HasIndex("MaChuDe");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("TraLoiHoiDaps");
                });

            modelBuilder.Entity("backend.Models.TuongTacNguoiDung", b =>
                {
                    b.Property<long>("MaTuongTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaTuongTac"));

                    b.Property<string>("LoaiTuongTac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaKhoaHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime2");

                    b.HasKey("MaTuongTac");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("TuongTacNguoiDungs");
                });

            modelBuilder.Entity("backend.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            DangHoatDong = true,
                            MoTa = "Học viên – quyền truy cập khóa học đã mua",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "Student"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            DangHoatDong = true,
                            MoTa = "Giảng viên – quyền tạo và quản lý khóa học",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "Instructor"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            DangHoatDong = true,
                            MoTa = "Quản trị viên – toàn quyền hệ thống",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            DangHoatDong = true,
                            MoTa = "Giám đốc tài chính – duyệt rút tiền và hoàn tiền",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "CFO"
                        },
                        new
                        {
                            MaVaiTro = 5,
                            DangHoatDong = true,
                            MoTa = "Giám đốc marketing – quản lý chiến dịch",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "CMO"
                        },
                        new
                        {
                            MaVaiTro = 6,
                            DangHoatDong = true,
                            MoTa = "Kiểm duyệt viên – duyệt nội dung khóa học",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "Moderator"
                        },
                        new
                        {
                            MaVaiTro = 7,
                            DangHoatDong = true,
                            MoTa = "Nhân viên hỗ trợ khách hàng",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "CS"
                        });
                });

            modelBuilder.Entity("backend.Models.VaiTroNguoiDung", b =>
                {
                    b.Property<int>("MaVaiTroNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTroNguoiDung"));

                    b.Property<Guid?>("GanBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGanVaiTro")
                        .HasColumnType("datetime2");

                    b.HasKey("MaVaiTroNguoiDung");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("VaiTroNguoiDungs");
                });

            modelBuilder.Entity("backend.Models.YeuCauRutTien", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<Guid?>("DuyetBoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaGiangVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienYeuCau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThanhToanLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("DuyetBoi");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("YeuCauRutTiens");
                });

            modelBuilder.Entity("backend.Models.BaiGiang", b =>
                {
                    b.HasOne("backend.Models.Chuong", "Chuong")
                        .WithMany()
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.TaiNguyenSo", "TaiNguyenSo")
                        .WithMany()
                        .HasForeignKey("MaTaiNguyen");

                    b.Navigation("Chuong");

                    b.Navigation("TaiNguyenSo");
                });

            modelBuilder.Entity("backend.Models.BaiKiemTra", b =>
                {
                    b.HasOne("backend.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBaiGiang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiGiang");
                });

            modelBuilder.Entity("backend.Models.CauHoi", b =>
                {
                    b.HasOne("backend.Models.BaiKiemTra", "BaiKiemTra")
                        .WithMany()
                        .HasForeignKey("MaBaiKiemTra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiKiemTra");
                });

            modelBuilder.Entity("backend.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.ChienDich", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("TaoBoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.ChuDeHoiDap", b =>
                {
                    b.HasOne("backend.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBaiGiang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiGiang");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("backend.Models.ChungChi", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.ChuoiHocLienTiep", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("backend.Models.Chuong", b =>
                {
                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.DanhGia", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.DanhMuc", b =>
                {
                    b.HasOne("backend.Models.DanhMuc", "DanhMucCha")
                        .WithMany()
                        .HasForeignKey("MaDanhMucCha");

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("backend.Models.DapAnHocVien", b =>
                {
                    b.HasOne("backend.Models.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.LanLamBai", "LanLamBai")
                        .WithMany()
                        .HasForeignKey("MaLanLam")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.LuaChonDapAn", "LuaChonDapAn")
                        .WithMany()
                        .HasForeignKey("MaLuaChonDaChon");

                    b.Navigation("CauHoi");

                    b.Navigation("LanLamBai");

                    b.Navigation("LuaChonDapAn");
                });

            modelBuilder.Entity("backend.Models.DiemDanh", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.LichHoc", "LichHoc")
                        .WithMany()
                        .HasForeignKey("MaLichHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("backend.Models.DonHang", b =>
                {
                    b.HasOne("backend.Models.GiamGia", "GiamGiaApDung")
                        .WithMany()
                        .HasForeignKey("MaGiamGia");

                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiamGiaApDung");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("backend.Models.GhiChu", b =>
                {
                    b.HasOne("backend.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBaiGiang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiGiang");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("backend.Models.GhiDanh", b =>
                {
                    b.HasOne("backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang");

                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.GiamGia", b =>
                {
                    b.HasOne("backend.Models.ChienDich", "ChienDich")
                        .WithMany()
                        .HasForeignKey("MaChienDich");

                    b.HasOne("backend.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien");

                    b.Navigation("ChienDich");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("backend.Models.GioHang", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("backend.Models.HoSoGiangVien", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.HoSoNhanVien", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.HoanTien", b =>
                {
                    b.HasOne("backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("XuLyBoi");

                    b.Navigation("DonHang");

                    b.Navigation("HocVien");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("backend.Models.KhoaHoc", b =>
                {
                    b.HasOne("backend.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.TaiNguyenSo", "VideoGioiThieu")
                        .WithMany()
                        .HasForeignKey("MaVideoGioiThieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("GiangVien");

                    b.Navigation("VideoGioiThieu");
                });

            modelBuilder.Entity("backend.Models.LanLamBai", b =>
                {
                    b.HasOne("backend.Models.BaiKiemTra", "BaiKiemTra")
                        .WithMany()
                        .HasForeignKey("MaBaiKiemTra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiKiemTra");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("backend.Models.LichHoc", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.LuaChonDapAn", b =>
                {
                    b.HasOne("backend.Models.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("backend.Models.MaHoaVideo", b =>
                {
                    b.HasOne("backend.Models.TaiNguyenSo", "TaiNguyenSo")
                        .WithMany()
                        .HasForeignKey("MaTaiNguyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiNguyenSo");
                });

            modelBuilder.Entity("backend.Models.MaOtp", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.MatHangGioHang", b =>
                {
                    b.HasOne("backend.Models.GioHang", "GioHang")
                        .WithMany()
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.NhanKhoaHoc", b =>
                {
                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NhanTuKhoa", "NhanTuKhoa")
                        .WithMany()
                        .HasForeignKey("MaNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NhanTuKhoa");
                });

            modelBuilder.Entity("backend.Models.PhanHoiPhieu", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.PhieuHoTro", "PhieuHoTro")
                        .WithMany()
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("PhieuHoTro");
                });

            modelBuilder.Entity("backend.Models.PhienLamViec", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.PhieuHoTro", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("MaNguoiGuiYeuCau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "NhanVienPhanCong")
                        .WithMany()
                        .HasForeignKey("PhanCongCho");

                    b.Navigation("NguoiGui");

                    b.Navigation("NhanVienPhanCong");
                });

            modelBuilder.Entity("backend.Models.SoCaiKeToan", b =>
                {
                    b.HasOne("backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.TaiNguyenSo", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("TaiLenBoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.ThongBaoKhoaHoc", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.ThongKeThoatBaiHoc", b =>
                {
                    b.HasOne("backend.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBaiGiang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiGiang");
                });

            modelBuilder.Entity("backend.Models.TienDoHocTap", b =>
                {
                    b.HasOne("backend.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBaiGiang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.GhiDanh", "GhiDanh")
                        .WithMany()
                        .HasForeignKey("MaGhiDanh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiGiang");

                    b.Navigation("GhiDanh");
                });

            modelBuilder.Entity("backend.Models.TongHopDoanhThuNgay", b =>
                {
                    b.HasOne("backend.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("backend.Models.TraLoiHoiDap", b =>
                {
                    b.HasOne("backend.Models.ChuDeHoiDap", "ChuDe")
                        .WithMany()
                        .HasForeignKey("MaChuDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.TuongTacNguoiDung", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.VaiTroNguoiDung", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("backend.Models.YeuCauRutTien", b =>
                {
                    b.HasOne("backend.Models.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("DuyetBoi");

                    b.HasOne("backend.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("NguoiDuyet");
                });
#pragma warning restore 612, 618
        }
    }
}
